DROP TABLE IF EXISTS `scc`.`MapaDaForca` ;

CREATE TABLE IF NOT EXISTS `scc`.`MapaDaForca` (
  `cel_previsto` SMALLINT NULL DEFAULT 0,
  `tc_previsto` SMALLINT NULL DEFAULT 0,
  `maj_previsto` SMALLINT NULL DEFAULT 0,
  `cap_previsto` SMALLINT NULL DEFAULT 0,
  `1ten_previsto` SMALLINT NULL DEFAULT 0,
  `2ten_previsto` SMALLINT NULL DEFAULT 0,
  `aspof_previsto` SMALLINT NULL DEFAULT 0,
  `cel_existente` SMALLINT NULL DEFAULT 0,
  `tc_existente` SMALLINT NULL DEFAULT 0,
  `maj_existente` SMALLINT NULL DEFAULT 0,
  `cap_existente` SMALLINT NULL DEFAULT 0,
  `1ten_existente` SMALLINT NULL DEFAULT 0,
  `2ten_existente` SMALLINT NULL DEFAULT 0,
  `aspof_existente` SMALLINT NULL DEFAULT 0,
  `sten_previsto` SMALLINT NULL DEFAULT 0,
  `1sgt_previsto` SMALLINT NULL DEFAULT 0,
  `2sgt_previsto` SMALLINT NULL DEFAULT 0,
  `3sgt_previsto` SMALLINT NULL DEFAULT 0,
  `cb_previsto` SMALLINT NULL DEFAULT 0,
  `cbev_previsto` SMALLINT NULL DEFAULT 0,
  `sdep_previsto` SMALLINT NULL DEFAULT 0,
  `sdev_previsto` SMALLINT NULL DEFAULT 0,
  `sten_existente` SMALLINT NULL DEFAULT 0,
  `1sgt_existente` SMALLINT NULL DEFAULT 0,
  `2sgt_existente` SMALLINT NULL DEFAULT 0,
  `3sgt_existente` SMALLINT NULL DEFAULT 0,
  `cb_existente` SMALLINT NULL DEFAULT 0,
  `cbev_existente` SMALLINT NULL DEFAULT 0,
  `sdep_existente` SMALLINT NULL DEFAULT 0,
  `sdev_existente` SMALLINT NULL DEFAULT 0,
  `cel_adido` SMALLINT NULL DEFAULT 0,
  `tc_adido` SMALLINT NULL DEFAULT 0,
  `maj_adido` SMALLINT NULL DEFAULT 0,
  `cap_adido` SMALLINT NULL DEFAULT 0,
  `1ten_adido` SMALLINT NULL DEFAULT 0,
  `2ten_adido` SMALLINT NULL DEFAULT 0,
  `aspof_adido` SMALLINT NULL DEFAULT 0,
  `sten_adido` SMALLINT NULL DEFAULT 0,
  `1sgt_adido` SMALLINT NULL DEFAULT 0,
  `2sgt_adido` SMALLINT NULL DEFAULT 0,
  `3sgt_adido` SMALLINT NULL DEFAULT 0,
  `cb_adido` SMALLINT NULL DEFAULT 0,
  `cbev_adido` SMALLINT NULL DEFAULT 0,
  `sdep_adido` SMALLINT NULL DEFAULT 0,
  `sdev_adido` SMALLINT NULL DEFAULT 0,
  `cel_encostado` SMALLINT NULL DEFAULT 0,
  `tc_encostado` SMALLINT NULL DEFAULT 0,
  `maj_encostado` SMALLINT NULL DEFAULT 0,
  `cap_encostado` SMALLINT NULL DEFAULT 0,
  `1ten_encostado` SMALLINT NULL DEFAULT 0,
  `2ten_encostado` SMALLINT NULL DEFAULT 0,
  `aspof_encostado` SMALLINT NULL DEFAULT 0,
  `sten_encostado` SMALLINT NULL DEFAULT 0,
  `1sgt_encostado` SMALLINT NULL DEFAULT 0,
  `2sgt_encostado` SMALLINT NULL DEFAULT 0,
  `3sgt_encostado` SMALLINT NULL DEFAULT 0,
  `cb_encostado` SMALLINT NULL DEFAULT 0,
  `cbev_encostado` SMALLINT NULL DEFAULT 0,
  `sdep_encostado` SMALLINT NULL DEFAULT 0,
  `sdev_encostado` SMALLINT NULL DEFAULT 0)
ENGINE = InnoDB;

START TRANSACTION;
USE `scc`;
INSERT INTO `scc`.`MapaDaForca` (`cel_previsto`, `tc_previsto`, `maj_previsto`, `cap_previsto`, `1ten_previsto`, `2ten_previsto`, `aspof_previsto`, `cel_existente`, `tc_existente`, `maj_existente`, `cap_existente`, `1ten_existente`, `2ten_existente`, `aspof_existente`, `sten_previsto`, `1sgt_previsto`, `2sgt_previsto`, `3sgt_previsto`, `cb_previsto`, `cbev_previsto`, `sdep_previsto`, `sdev_previsto`, `sten_existente`, `1sgt_existente`, `2sgt_existente`, `3sgt_existente`, `cb_existente`, `cbev_existente`, `sdep_existente`, `sdev_existente`, `cel_adido`, `tc_adido`, `maj_adido`, `cap_adido`, `1ten_adido`, `2ten_adido`, `aspof_adido`, `sten_adido`, `1sgt_adido`, `2sgt_adido`, `3sgt_adido`, `cb_adido`, `cbev_adido`, `sdep_adido`, `sdev_adido`, `cel_encostado`, `tc_encostado`, `maj_encostado`, `cap_encostado`, `1ten_encostado`, `2ten_encostado`, `aspof_encostado`, `sten_encostado`, `1sgt_encostado`, `2sgt_encostado`, `3sgt_encostado`, `cb_encostado`, `cbev_encostado`, `sdep_encostado`, `sdev_encostado`) VALUES (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

COMMIT;
